#!/bin/bash

currentscriptpath()
{
    local fullpath=`echo "$(readlink -f $0)"`
    local fullpath_length=`echo ${#fullpath}`
    local scriptname="$(basename $0)"
    local scriptname_length=`echo ${#scriptname}`
    local result_length=`echo $fullpath_length - $scriptname_length - 1 | bc`
    local result=`echo $fullpath | head -c $result_length`
    echo $result
}

current="$(dirname "$0")"

echo $current

cd $current/trunk/Line_Wars
pwd
java -Xmx2048m -cp bin menu.WindowTester